# Pandas: Data Manipulation & Analysis

Learn **Pandas**, a Python library for working with data.

Pandas gives fast tools for tables of data. It works with **NumPy**. It also works well with **Matplotlib** and **Seaborn**.

---

## 1. Introduction to Pandas

### Why Use Pandas?
Plain Python needs loops and dictionaries for data work. Pandas does it in a few lines.

### Core Data Structures
Pandas has two main data structures:
* **Series**: a 1D labeled array. Holds any data type.
* **DataFrame**: a 2D table with rows and columns.

| Feature | Series 🟢 | DataFrame 🔵 |
| :--- | :--- | :--- |
| **Dimensions** | 1D (Single column) | 2D (Rows & Columns table) |
| **Analogy** | Single Excel column | Entire Excel sheet |
| **Labels** | Index labels | Row index & Column headers |

## 2. Setting Up
Import Pandas as `pd`. Also import `numpy` as `np`.

In [113]:
import pandas as pd
import numpy as np

## 3. Pandas Series

A **Series** is one column of data with an index. If you don't set an index, Pandas makes one, starting at 0.

### Creating a Series
Build a Series from a Python list.

In [114]:
# Create a Series from a list
temperatures = [15, 30, 45, 60]
temp_series = pd.Series(temperatures)
print(temp_series)

0    15
1    30
2    45
3    60
dtype: int64

In [115]:
# Create a Series with mixed types
mixed_data = [102, "Soren", 72.5, True]
mixed_series = pd.Series(mixed_data)
print(mixed_series)

0      102
1    Soren
2     72.5
3     True
dtype: object

### Accessing Series Data
Get a value by its index position, like a list. You can also slice a range.

In [116]:
# Get value by index
print("Value at index 2:", temp_series[2])

# Slice values (index 1 to 3)
print("\nSlicing index 1 to 3:")
print(temp_series[1:3])

Value at index 2: 45

Slicing index 1 to 3:
1    30
2    45
dtype: int64

## 4. Pandas DataFrames

A **DataFrame** is a full table. It has a row index and column names.

### The DataFrame Constructor
`pd.DataFrame()` creates a new DataFrame.

### Creating a DataFrame from a Dictionary
A common way: use a dictionary. Keys become column names. Values become the column data.

In [117]:
# Create a DataFrame from a dictionary
student_dict = {
    "Name": ["Ahmed", "Mohamed", "Moaz"],
    "Age": [25, 30, 22],
    "City": ["Cairo", "Giza", "Alexandria"]
}
df_students = pd.DataFrame(student_dict)
df_students

      Name  Age        City
0    Ahmed   25       Cairo
1  Mohamed   30        Giza
2     Moaz   22  Alexandria

### Custom Indexing in DataFrames
Set your own row labels with the `index` parameter.

In [118]:
# Create a DataFrame with custom index
user_dict = {
    "Name": ["Ahmed", "Mohamed", "Moaz"],
    "Smoke_Status": [0, 1, 1],
    "Age": [20, 11, 10]
}
df_users = pd.DataFrame(user_dict, index=["User_A", "User_B", "User_C"])
df_users

           Name  Smoke_Status  Age
User_A    Ahmed             0   20
User_B  Mohamed             1   11
User_C     Moaz             1   10

## 5. Loading and Inspecting Datasets

Data usually comes from files, not code. **CSV** (Comma-Separated Values) is the most common format.

### Raw String Prefix `r` for File Paths
Backslashes (`\`) in a file path can cause errors in Python.
* Use `r"C:\data\file.csv"` to fix this.
* Or use forward slashes: `"C:/data/file.csv"`.

### Loading a CSV File
Use `pd.read_csv()` to load a CSV file.

In [119]:
# Read a CSV file into a DataFrame
df_covid = pd.read_csv("../data/covid19_counties_2023.csv")
df_covid.head()

       date   county    state    fips  cases  deaths
0  1/1/2023  Autauga  Alabama  1001.0  18961   230.0
1  1/1/2023  Baldwin  Alabama  1003.0  67496   719.0
2  1/1/2023  Barbour  Alabama  1005.0   7027   111.0
3  1/1/2023     Bibb  Alabama  1007.0   7692   108.0
4  1/1/2023   Blount  Alabama  1009.0  17731   260.0

### Quick Data Inspection
Check the data before analyzing it.
* `head(n)`: first `n` rows (default 5).
* `tail(n)`: last `n` rows (default 5).
* `shape`: number of rows and columns.
* `columns`: list of column names.
* `info()`: column types and missing values.
* `describe()`: summary stats for numeric columns.

In [120]:
# Check dimensions
print("Dataset Shape (rows, columns):", df_covid.shape)

# View first and last few rows
print("\nFirst 3 rows:")
print(df_covid.head(3))

print("\nLast 2 rows:")
print(df_covid.tail(2))

Dataset Shape (rows, columns): (267009, 6)

First 3 rows:
       date   county    state    fips  cases  deaths
0  1/1/2023  Autauga  Alabama  1001.0  18961   230.0
1  1/1/2023  Baldwin  Alabama  1003.0  67496   719.0
2  1/1/2023  Barbour  Alabama  1005.0   7027   111.0

Last 2 rows:
             date    county    state     fips  cases  deaths
267007  3/23/2023  Washakie  Wyoming  56043.0   2700    51.0
267008  3/23/2023    Weston  Wyoming  56045.0   1906    23.0

In [121]:
# Display structural info
print("Columns:", df_covid.columns.tolist())
print("\n--- Detailed Information ---")
df_covid.info()

Columns: ['date', 'county', 'state', 'fips', 'cases', 'deaths']

--- Detailed Information ---
<class 'pandas.DataFrame'>
RangeIndex: 267009 entries, 0 to 267008
Data columns (total 6 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   date    267009 non-null  str
 1   county  267009 non-null  str
 2   state   267009 non-null  str
 3   fips    264023 non-null  float64
 4   cases   267009 non-null  int64
 5   deaths  260613 non-null  float64
dtypes: float64(2), int64(1), str(3)
memory usage: 12.2 MB

In [122]:
# Summary statistics
df_covid.describe ().round (2)

            fips       cases     deaths
count  264023.00   267009.00  260613.00
mean    31487.97    31464.73     352.21
std     16376.53   119311.92    1322.16
min      1001.00        0.00       0.00
25%     19035.00     3147.00      48.00
50%     30027.00     7955.00     111.00
75%     46121.00    20711.00     262.00
max     78030.00  3723182.00   45155.00

## 6. Selecting and Slicing Data

Pick columns, rows, or single values.

### Selecting Columns: Dot vs. Bracket Notation
1. **Dot Notation (`df.column_name`)**: short, but fails with spaces or method names.
2. **Bracket Notation (`df["column_name"]`)**: always works. Use a list for many columns: `df[["col1", "col2"]]`.

In [123]:
# Bracket notation (Recommended)
counties = df_covid["county"]
print(counties.head())

# Dot notation
print(df_covid.county.head())

0    Autauga
1    Baldwin
2    Barbour
3       Bibb
4     Blount
Name: county, dtype: str
0    Autauga
1    Baldwin
2    Barbour
3       Bibb
4     Blount
Name: county, dtype: str

### Selecting Single Values
Select a column, then pick a value from it.

In [124]:
# Get the first value in "county" column
first_county = df_covid["county"][0]
print("First county in list:", first_county)

First county in list: Autauga

### Advanced Indexing: `.loc`, `.iloc`, `.at`, and `.iat`

* **`.loc`**: select by label.
* **`.iloc`**: select by position.
* **`.at`**: fast, single value by label.
* **`.iat`**: fast, single value by position.

| Indexer | Access Type | Returns | Speed | Use Case |
| :--- | :--- | :--- | :--- | :--- |
| **`.loc`** | Label-based | Series, DataFrame, or value | Standard | Slicing rows/columns by name |
| **`.iloc`** | Position-based | Series, DataFrame, or value | Standard | Slicing rows/columns by index number |
| **`.at`** | Label-based | Single scalar value | **Fastest** | Fetching a single cell value by name |
| **`.iat`** | Position-based | Single scalar value | **Fastest** | Fetching a single cell value by position |

#### Examples using `.loc` (Label-Based)

In [125]:
# Select a single row by index label
print("First row label-based selection:\n", df_covid.loc[0])

# Select row 0, column "county"
print("\nCounty at index 0:", df_covid.loc[0, "county"])

# Select multiple columns for a single row
print("\nMultiple columns for row 0:\n", df_covid.loc[0, ["date", "cases", "deaths"]])

# Select specific rows and specific columns
print("\nMultiple rows & columns:\n", df_covid.loc[[0, 3, 5], ["county", "state", "cases"]])

# Slice by label (includes both ends)
print("\nLabel slice 0 to 5:\n", df_covid.loc[0:5, ["date", "cases"]])

First row label-based selection:
 date      1/1/2023
county     Autauga
state      Alabama
fips        1001.0
cases        18961
deaths       230.0
Name: 0, dtype: object

County at index 0: Autauga

Multiple columns for row 0:
 date      1/1/2023
cases        18961
deaths       230.0
Name: 0, dtype: object

Multiple rows & columns:
     county    state  cases
0  Autauga  Alabama  18961
3     Bibb  Alabama   7692
5  Bullock  Alabama   2886

Label slice 0 to 5:
        date  cases
0  1/1/2023  18961
1  1/1/2023  67496
2  1/1/2023   7027
3  1/1/2023   7692
4  1/1/2023  17731
5  1/1/2023   2886

#### Examples using `.iloc` (Position-Based)

In [126]:
# Select first row by position
print("First row position-based selection:\n", df_covid.iloc[0])

# Select first row (0) and second column (1)
print("\nValue at row 0, col 1:", df_covid.iloc[0, 1])

# Slice rows 0 to 5 (5 not included)
print("\nFirst 5 rows slicing:\n", df_covid.iloc[0:5, :])

# Select specific rows and columns by position
print("\nNon-contiguous selection:\n", df_covid.iloc[[0, 2, 5], [0, 1, 4]])

First row position-based selection:
 date      1/1/2023
county     Autauga
state      Alabama
fips        1001.0
cases        18961
deaths       230.0
Name: 0, dtype: object

Value at row 0, col 1: Autauga

First 5 rows slicing:
        date   county    state    fips  cases  deaths
0  1/1/2023  Autauga  Alabama  1001.0  18961   230.0
1  1/1/2023  Baldwin  Alabama  1003.0  67496   719.0
2  1/1/2023  Barbour  Alabama  1005.0   7027   111.0
3  1/1/2023     Bibb  Alabama  1007.0   7692   108.0
4  1/1/2023   Blount  Alabama  1009.0  17731   260.0

Non-contiguous selection:
        date   county  cases
0  1/1/2023  Autauga  18961
2  1/1/2023  Barbour   7027
5  1/1/2023  Bullock   2886

#### Fast Scalar Access: `.at` and `.iat`
Use `.at` and `.iat` for one value only. They run faster.

In [127]:
# Fast label access
value_at = df_covid.at [2, "cases"]
print("Fast label access at row 2, cases:", value_at)

# Fast position access
value_iat = df_covid.iat[2, 4]
print("Fast position access at row 2, col 4:", value_iat)

Fast label access at row 2, cases: 7027
Fast position access at row 2, col 4: 7027

## 7. Filtering with Boolean Conditions

Filter rows using a condition. This makes a **boolean mask** (`True`/`False` values).

### Simple Filtering

In [128]:
# Mask: cases greater than 1900
mask = df_covid["cases"] > 1900

# Filter using the mask
df_filtered = df_covid[mask]
df_filtered.head()

       date   county    state    fips  cases  deaths
0  1/1/2023  Autauga  Alabama  1001.0  18961   230.0
1  1/1/2023  Baldwin  Alabama  1003.0  67496   719.0
2  1/1/2023  Barbour  Alabama  1005.0   7027   111.0
3  1/1/2023     Bibb  Alabama  1007.0   7692   108.0
4  1/1/2023   Blount  Alabama  1009.0  17731   260.0

### Combining Multiple Conditions
* **`&`** (AND): both must be True.
* **`|`** (OR): at least one is True.
* **`~`** (NOT): flips the condition.

Note: put each condition in `()`.

In [129]:
# Cases > 1900 AND deaths > 22
df_and = df_covid [(df_covid["cases"] > 1900) & (df_covid["deaths"] > 22)]
df_and.head ()

       date   county    state    fips  cases  deaths
0  1/1/2023  Autauga  Alabama  1001.0  18961   230.0
1  1/1/2023  Baldwin  Alabama  1003.0  67496   719.0
2  1/1/2023  Barbour  Alabama  1005.0   7027   111.0
3  1/1/2023     Bibb  Alabama  1007.0   7692   108.0
4  1/1/2023   Blount  Alabama  1009.0  17731   260.0

In [130]:
# Cases > 20000 OR deaths > 3000
df_or = df_covid[(df_covid["cases"] > 20000) | (df_covid["deaths"] > 3000)]
df_or.head()

        date   county    state    fips  cases  deaths
1   1/1/2023  Baldwin  Alabama  1003.0  67496   719.0
7   1/1/2023  Calhoun  Alabama  1015.0  39458   665.0
16  1/1/2023  Colbert  Alabama  1033.0  20165   275.0
21  1/1/2023  Cullman  Alabama  1043.0  30119   391.0
24  1/1/2023   DeKalb  Alabama  1049.0  21738   350.0

### Filtering with `.isin()`
Use `.isin()` to check against a list of values, instead of writing many OR conditions.

In [131]:
# Filter rows where state is in the list
target_states = ["Wyoming", "Texas"]
df_states = df_covid[df_covid["state"].isin (target_states)]
df_states.head()

          date    county  state     fips  cases  deaths
2628  1/1/2023  Anderson  Texas  48001.0  10771   252.0
2629  1/1/2023   Andrews  Texas  48003.0   4901    73.0
2630  1/1/2023  Angelina  Texas  48005.0  16747   497.0
2631  1/1/2023   Aransas  Texas  48007.0   5378    98.0
2632  1/1/2023    Archer  Texas  48009.0   2563    32.0

In [132]:
# Filter out states in the list (~ means NOT)
df_no_states = df_covid[~df_covid["state"].isin(target_states)]
df_no_states.head()

       date   county    state    fips  cases  deaths
0  1/1/2023  Autauga  Alabama  1001.0  18961   230.0
1  1/1/2023  Baldwin  Alabama  1003.0  67496   719.0
2  1/1/2023  Barbour  Alabama  1005.0   7027   111.0
3  1/1/2023     Bibb  Alabama  1007.0   7692   108.0
4  1/1/2023   Blount  Alabama  1009.0  17731   260.0

### Filtering Missing Values
Use `.isnull()` and `.notnull()` to filter by missing (`NaN`) values.

In [133]:
# Filter rows where deaths column is not null
df_valid_deaths = df_covid[df_covid["deaths"].notnull()]
df_valid_deaths.head()

       date   county    state    fips  cases  deaths
0  1/1/2023  Autauga  Alabama  1001.0  18961   230.0
1  1/1/2023  Baldwin  Alabama  1003.0  67496   719.0
2  1/1/2023  Barbour  Alabama  1005.0   7027   111.0
3  1/1/2023     Bibb  Alabama  1007.0   7692   108.0
4  1/1/2023   Blount  Alabama  1009.0  17731   260.0

### Querying Data with `.query()`
`.query()` lets you filter using a text condition, like SQL.

In [134]:
# Filter with .query()
df_query = df_covid.query("state == 'Wyoming' and cases > 20000 and deaths < 10000")
df_query.head()

          date   county    state     fips  cases  deaths
3242  1/1/2023  Laramie  Wyoming  56021.0  31151   318.0
3244  1/1/2023  Natrona  Wyoming  56025.0  25543   298.0
6497  1/2/2023  Laramie  Wyoming  56021.0  31151   318.0
6499  1/2/2023  Natrona  Wyoming  56025.0  25543   298.0
9751  1/3/2023  Laramie  Wyoming  56021.0  31221   318.0

## 8. Modifying and Assigning Data

Update values, copy columns, or add new columns.

### Updating Values in-place
Use `.loc` to change specific cells.

In [135]:
# Create a working copy of the dataset
df_mod = df_covid.copy()

# Update the county at index 0
df_mod.loc[0, "county"] = "Giza"
print("Updated county at index 0:", df_mod.loc[0, "county"])

Updated county at index 0: Giza

### Adding a Constant Column
Assign one value to create a new column.

In [136]:
# Add a column with one value for all rows
df_mod["country"] = "USA"
df_mod[["county", "state", "country"]].head ()

    county    state country
0     Giza  Alabama     USA
1  Baldwin  Alabama     USA
2  Barbour  Alabama     USA
3     Bibb  Alabama     USA
4   Blount  Alabama     USA

### Conditional Assignments
Assign values based on a condition. For Yes/No labels, use `numpy.where()`.

In [137]:
# Add a boolean column for high cases
df_mod["high_cases"] = df_mod["cases"] > 1500

# Add a Yes/No column with np.where
df_mod["high_cases_label"] = np.where(df_mod["cases"] > 8000, "Yes", "No")
df_mod[["county", "cases", "high_cases", "high_cases_label"]].head()

    county  cases  high_cases high_cases_label
0     Giza  18961        True              Yes
1  Baldwin  67496        True              Yes
2  Barbour   7027        True               No
3     Bibb   7692        True               No
4   Blount  17731        True              Yes

### Creating Calculated Columns
Make new columns using math on existing columns.

In [138]:
# Calculate mortality rate (deaths / cases)
df_mod["mortality_rate"] = df_mod["deaths"] / df_mod["cases"]
df_mod[["county", "cases", "deaths", "mortality_rate"]].head()

    county  cases  deaths  mortality_rate
0     Giza  18961   230.0        0.012130
1  Baldwin  67496   719.0        0.010652
2  Barbour   7027   111.0        0.015796
3     Bibb   7692   108.0        0.014041
4   Blount  17731   260.0        0.014664

### Creating Columns with `.assign()` (Chaining)
`.assign()` makes a new column without changing the original DataFrame. Good for chaining.

In [139]:
# .assign() returns a new DataFrame
df_assigned = df_covid.assign(mortality_rate = df_covid["deaths"] / df_covid["cases"])
df_assigned[["county", "cases", "deaths", "mortality_rate"]].head()

    county  cases  deaths  mortality_rate
0  Autauga  18961   230.0        0.012130
1  Baldwin  67496   719.0        0.010652
2  Barbour   7027   111.0        0.015796
3     Bibb   7692   108.0        0.014041
4   Blount  17731   260.0        0.014664

### Updating Multiple Columns at Once

In [140]:
# Multiply both cases and deaths by 2
df_scale = df_covid[["cases", "deaths"]].copy()
df_scale[["cases", "deaths"]] = df_scale[["cases", "deaths"]] * 2
df_scale.head()

    cases  deaths
0   37922   460.0
1  134992  1438.0
2   14054   222.0
3   15384   216.0
4   35462   520.0

### Renaming Columns
Rename some columns with `.rename(columns={})`. Rename all columns by setting `.columns` directly.

In [141]:
# Rename selectively
df_renamed = df_covid.rename(columns={"cases": "total_cases", "deaths": "total_deaths"})
print("Selective rename columns:", df_renamed.columns.tolist())

Selective rename columns: ['date', 'county', 'state', 'fips', 'total_cases', 'total_deaths']

In [142]:
# Replace all column names
df_custom_cols = df_covid.copy()
df_custom_cols.columns = ["Reported_Date", "County_Name", "State_Name", "FIPS_Code", "Confirmed_Cases", "Recorded_Deaths"]
df_custom_cols.head(2)

,Reported_Date,County_Name,State_Name,FIPS_Code,Confirmed_Cases,Recorded_Deaths
0,1/1/2023,Autauga,Alabama,1001.0,18961,230.0
1,1/1/2023,Baldwin,Alabama,1003.0,67496,719.0

## 9. Data Quality and Cleaning

Real data has duplicates, missing values (`NaN`), and errors.

### Checking for Duplicates and Missing Values
Load a diabetes dataset to check data quality.

In [143]:
# Load diabetes dataset
df_diabetes = pd.read_csv("../data/diabetes.csv")
print("Diabetes Shape:", df_diabetes.shape)

# Count duplicate rows
print("Duplicate rows count:", df_diabetes.duplicated().sum())

# Check for missing values
print("\nMissing values count per column:")
print(df_diabetes.isna().sum())

Diabetes Shape: (772, 9)
Duplicate rows count: 4

Missing values count per column:
Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               2
Insulin                     0
BMI                         7
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

### Dropping Duplicates and Handling Missing Values
1. **`drop_duplicates()`**: remove duplicate rows.
2. **`fillna()`**: fill missing values (with mean, median, etc).
3. **`dropna()`**: remove rows with missing values.

In [144]:
# Create clean copy
clean_diabetes = df_diabetes.drop_duplicates().copy()

# Fill missing BMI with the median
clean_diabetes["BMI"] = clean_diabetes["BMI"].fillna(clean_diabetes["BMI"].median())

# Drop rows where SkinThickness is missing
clean_diabetes = clean_diabetes.dropna(subset=["SkinThickness"])

print("Shape after cleaning:", clean_diabetes.shape)
print("\nMissing values after cleaning:")
print(clean_diabetes.isna().sum())

Shape after cleaning: (766, 9)

Missing values after cleaning:
Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

### Handling Missing Values with Group Statistics
A global average isn't always the best fill. For COVID deaths, each state's own average works better than the national average.

Use `.groupby()` with `.transform()` to do this.

In [145]:
# Fill missing deaths with each state's mean
df_clean_covid = df_covid.copy()
df_clean_covid["deaths"] = df_clean_covid.groupby("state")["deaths"].transform(lambda x: x.fillna(x.mean()))

# Drop any remaining missing values
df_clean_covid = df_clean_covid.dropna()
print("Remaining missing values:", df_clean_covid.isna().sum())

Remaining missing values: date      0
county    0
state     0
fips      0
cases     0
deaths    0
dtype: int64

## 10. Basic Data Analysis

Pandas has built-in stats functions for quick analysis.

### Numeric Aggregations
Common functions: `.mean()`, `.median()`, `.std()`, `.sum()`, `.max()`.

In [146]:
print("Average Cases:", df_covid["cases"].mean())
print("Median Cases:", df_covid["cases"].median())
print("Standard Deviation:", df_covid["cases"].std())

Average Cases: 31464.733143826612
Median Cases: 7955.0
Standard Deviation: 119311.9239552022

### Exploring Categorical Columns
For non-numeric columns:
* **`.unique()`**: list unique values.
* **`.value_counts()`**: count each value.

In [147]:
# Unique states
print("Unique States:", df_covid["state"].unique()[:10])

# Value counts
print("\nTop 5 states by reports count:")
print(df_covid["state"].value_counts().head())

# Show proportions, not counts
print("\nState report proportions (top 5):")
print(df_covid["state"].value_counts(normalize=True).head())

# Sort smallest to largest
print("\nStates with fewest reports (bottom 5):")
print(df_covid["state"].value_counts(ascending=True).head())

Unique States: <StringArray>
[             'Alabama',               'Alaska',       'American Samoa',
              'Arizona',             'Arkansas',           'California',
             'Colorado',          'Connecticut',             'Delaware',
 'District of Columbia']
Length: 10, dtype: str

Top 5 states by reports count:
state
Texas       20975
Georgia     13120
Virginia    10973
Kentucky     9912
Missouri     9594
Name: count, dtype: int64

State report proportions (top 5):
state
Texas       0.078555
Georgia     0.049137
Virginia    0.041096
Kentucky    0.037122
Missouri    0.035931
Name: proportion, dtype: float64

States with fewest reports (bottom 5):
state
American Samoa               82
District of Columbia         82
Guam                         82
Northern Mariana Islands    246
Virgin Islands              293
Name: count, dtype: int64

## 11. Data Transformations: `.map()` and `.apply()`

Apply your own functions to change data.

### Element-Wise Mapping with `.map()`
`.map()` works on a **Series**, one value at a time. Use it with functions, dictionaries, or formatting.

In [148]:
# Map state names to uppercase
df_trans_ex = df_covid.head(5).copy()
df_trans_ex["state_upper"] = df_trans_ex["state"].map(str.upper)
df_trans_ex[["state", "state_upper"]]

     state state_upper
0  Alabama     ALABAMA
1  Alabama     ALABAMA
2  Alabama     ALABAMA
3  Alabama     ALABAMA
4  Alabama     ALABAMA

### Applying Functions with `.apply()`
`.apply()` works on **Series** and **DataFrames**. Use it with custom functions or lambda functions.

In [149]:
# Function to classify severity
def classify_severity(cases):
    if cases > 50000:
        return "High Severity"
    elif cases > 20000:
        return "Medium Severity"
    else:
        return "Low Severity"

# Apply the function to the cases column
df_trans_ex["severity"] = df_trans_ex["cases"].apply(classify_severity)
df_trans_ex[["county", "cases", "severity"]]

    county  cases       severity
0  Autauga  18961   Low Severity
1  Baldwin  67496  High Severity
2  Barbour   7027   Low Severity
3     Bibb   7692   Low Severity
4   Blount  17731   Low Severity

### Element-Wise DataFrame Operations: `.map()`
Old Pandas used `.applymap()` for this.
**Note:** New Pandas (2.1.0+) uses **`.map()`** instead.

In [150]:
# Format numbers in multiple columns
df_numeric = df_covid[["cases", "deaths"]].head(3).copy()
df_formatted = df_numeric.map(lambda val: f"{val:,.1f}")
df_formatted

      cases deaths
0  18,961.0  230.0
1  67,496.0  719.0
2   7,027.0  111.0

## 12. Grouping and Aggregating: `.groupby()`

`groupby()` splits data into groups, then applies a function to each group.

### Grouping by One Column

In [155]:
# Sum cases per state (top 5)
df_covid.groupby("state")["cases"].sum().sort_values(ascending=False).head()

state
California    985844951
Texas         678812946
Florida       609882039
New York      551095969
Illinois      331615853
Name: cases, dtype: int64

### Grouping by Multiple Columns

In [ ]:
# Mean cases per county in each state
df_covid.groupby(["state", "county"])["cases"].mean().sort_values(ascending=False).head()

             date      county    state     fips  cases  deaths
0        1/1/2023     Autauga  Alabama   1001.0  18961   230.0
1        1/1/2023     Baldwin  Alabama   1003.0  67496   719.0
2        1/1/2023     Barbour  Alabama   1005.0   7027   111.0
3        1/1/2023        Bibb  Alabama   1007.0   7692   108.0
4        1/1/2023      Blount  Alabama   1009.0  17731   260.0
...           ...         ...      ...      ...    ...     ...
267004  3/23/2023  Sweetwater  Wyoming  56037.0  12519   139.0
267005  3/23/2023       Teton  Wyoming  56039.0  12150    16.0
267006  3/23/2023       Uinta  Wyoming  56041.0   6416    43.0
267007  3/23/2023    Washakie  Wyoming  56043.0   2700    51.0
267008  3/23/2023      Weston  Wyoming  56045.0   1906    23.0

[267009 rows x 6 columns]

### Multiple Aggregations with `.agg()`
Use `.agg()` to compute different stats for different columns at once.

In [ ]:
# Aggregate multiple columns with multiple stats
df_multi_agg = df_covid.groupby("state").agg({
    "cases": ["sum", "mean", "max"],
    "deaths": ["sum", "mean"]
})
df_multi_agg.head()

                    cases                             deaths
                      sum           mean      max        sum         mean
state
Alabama         132949677   24185.860833   239299  1754751.0   319.219756
Alaska           25041519   10906.584930   123977   116890.0    50.910279
American Samoa     680865    8303.231707     8309     2788.0    34.000000
Arizona         197888351  160884.838211  1533874  2692880.0  2189.333333
Arkansas         81930363   13146.720635   128164  1057908.0   169.754172

### Group-Wise Filtering with `.filter()`
Remove whole groups based on a group-level condition.

In [ ]:
# Keep only states with cumulative cases greater than 100,000,000
df_large_states = df_covid.groupby("state").filter(lambda group: group["cases"].sum() > 100000000)
print("States matching group filter:", df_large_states["state"].unique())

States matching group filter: <StringArray>
[       'Alabama',        'Arizona',     'California',       'Colorado',
        'Florida',        'Georgia',       'Illinois',        'Indiana',
       'Kentucky',      'Louisiana',       'Maryland',  'Massachusetts',
       'Michigan',      'Minnesota',       'Missouri',     'New Jersey',
       'New York', 'North Carolina',           'Ohio',       'Oklahoma',
   'Pennsylvania', 'South Carolina',      'Tennessee',          'Texas',
       'Virginia',     'Washington',      'Wisconsin']
Length: 27, dtype: str

## 13. Sorting Data

Sort rows by column values.

### Basic Sorting

In [ ]:
# Sort by cases descending
df_covid.sort_values(by="cases", ascending=False).head()

             date       county       state    fips    cases   deaths
263957  3/23/2023  Los Angeles  California  6037.0  3723182  35960.0
260699  3/22/2023  Los Angeles  California  6037.0  3722448  35949.0
257444  3/21/2023  Los Angeles  California  6037.0  3721923  35937.0
254188  3/20/2023  Los Angeles  California  6037.0  3721276  35925.0
247673  3/18/2023  Los Angeles  California  6037.0  3720066  35890.0

### Sorting by Multiple Columns

In [ ]:
# Sort by state (A-Z) and cases (high-low)
df_covid.sort_values(by=["state", "cases"], ascending=[True, False]).head()

             date     county    state    fips   cases  deaths
260530  3/22/2023  Jefferson  Alabama  1073.0  239299  2536.0
263788  3/23/2023  Jefferson  Alabama  1073.0  239299  2536.0
237729  3/15/2023  Jefferson  Alabama  1073.0  239035  2535.0
240988  3/16/2023  Jefferson  Alabama  1073.0  239035  2535.0
244246  3/17/2023  Jefferson  Alabama  1073.0  239035  2535.0

### Combining Grouping and Sorting
To get the top `N` rows per group: sort first, then use `.head(N)`.

In [ ]:
# Top 2 counties per state based on cases
df_top_counties = df_covid.groupby("state").apply(
    lambda group: group.sort_values("cases", ascending=False).head(2)
)
df_top_counties.head(6)

                            date     county    fips   cases  deaths
state
Alabama        263788  3/23/2023  Jefferson  1073.0  239299  2536.0
               260530  3/22/2023  Jefferson  1073.0  239299  2536.0
Alaska         263821  3/23/2023  Anchorage  2020.0  123977   593.0
               257308  3/21/2023  Anchorage  2020.0  123977   593.0
American Samoa 55403   1/18/2023    Unknown     NaN    8309    34.0
               45641   1/15/2023    Unknown     NaN    8309    34.0

## 14. Combining DataFrames

Data often comes in separate parts. Use these functions to combine them.

### Stacking Data with `pd.concat()`
`pd.concat()` stacks rows (vertical) or columns (horizontal).

In [ ]:
# Create daily samples
df_day1 = df_covid[df_covid["date"] == "1/1/2023"].head(3)
df_day2 = df_covid[df_covid["date"] == "1/2/2023"].head(3)

print("Day 1 Sample:\n", df_day1[["date", "county", "cases"]])
print("\nDay 2 Sample:\n", df_day2[["date", "county", "cases"]])

Day 1 Sample:
        date   county  cases
0  1/1/2023  Autauga  18961
1  1/1/2023  Baldwin  67496
2  1/1/2023  Barbour   7027

Day 2 Sample:
           date   county  cases
3255  1/2/2023  Autauga  18961
3256  1/2/2023  Baldwin  67496
3257  1/2/2023  Barbour   7027

In [ ]:
# Stack Day 1 and Day 2 data vertically
df_stacked = pd.concat([df_day1, df_day2], ignore_index=True)
df_stacked[["date", "county", "cases"]]

       date   county  cases
0  1/1/2023  Autauga  18961
1  1/1/2023  Baldwin  67496
2  1/1/2023  Barbour   7027
3  1/2/2023  Autauga  18961
4  1/2/2023  Baldwin  67496
5  1/2/2023  Barbour   7027

### Merging Data with `pd.merge()`
`pd.merge()` joins DataFrames on a shared column, like a SQL JOIN.

#### Types of Joins (`how`)
* **`inner`** (default): only rows that match in both.
* **`left`**: all left rows, plus matches from right. No match = `NaN`.
* **`right`**: all right rows, plus matches from left. No match = `NaN`.
* **`outer`**: all rows from both. No match = `NaN`.

| Join Type (`how`) | Keep Left Unmatched | Keep Right Unmatched | Result Size |
| :--- | :--- | :--- | :--- |
| **`inner`** | ❌ No | ❌ No | Smallest |
| **`left`** | ✅ Yes | ❌ No | At least size of left |
| **`right`** | ❌ No | ✅ Yes | At least size of right |
| **`outer`** | ✅ Yes | ✅ Yes | Largest |

In [ ]:
# Create a population DataFrame
df_population = pd.DataFrame({
    "county": ["Autauga", "Baldwin", "Barbour"],
    "population": [55869, 227131, 24686]
})

# Left Join with COVID data
df_merged = pd.merge(df_covid.head(10), df_population, on="county", how="left")
df_merged[["date", "county", "state", "cases", "population"]]

       date    county    state  cases  population
0  1/1/2023   Autauga  Alabama  18961     55869.0
1  1/1/2023   Baldwin  Alabama  67496    227131.0
2  1/1/2023   Barbour  Alabama   7027     24686.0
3  1/1/2023      Bibb  Alabama   7692         NaN
4  1/1/2023    Blount  Alabama  17731         NaN
5  1/1/2023   Bullock  Alabama   2886         NaN
6  1/1/2023    Butler  Alabama   6185         NaN
7  1/1/2023   Calhoun  Alabama  39458         NaN
8  1/1/2023  Chambers  Alabama  10311         NaN
9  1/1/2023  Cherokee  Alabama   6456         NaN

### Join Types Comparison Example
See all four join types with two small DataFrames.

In [ ]:
# Create two small DataFrames
df_left = pd.DataFrame({
    "county": ["Autauga", "Baldwin", "Barbour", "Bibb"],
    "cases": [18961, 67496, 7027, 7692]
})
df_right = pd.DataFrame({
    "county": ["Autauga", "Baldwin", "Blount"],
    "population": [55869, 227131, 59852]
})

In [ ]:
# Inner Join
print("Inner Join:")
print(pd.merge(df_left, df_right, on="county", how="inner"))

Inner Join:
    county  cases  population
0  Autauga  18961       55869
1  Baldwin  67496      227131

In [ ]:
# Left Join
print("Left Join:")
print(pd.merge(df_left, df_right, on="county", how="left"))

Left Join:
    county  cases  population
0  Autauga  18961     55869.0
1  Baldwin  67496    227131.0
2  Barbour   7027         NaN
3     Bibb   7692         NaN

In [ ]:
# Right Join
print("Right Join:")
print(pd.merge(df_left, df_right, on="county", how="right"))

Right Join:
    county    cases  population
0  Autauga  18961.0       55869
1  Baldwin  67496.0      227131
2   Blount      NaN       59852

In [ ]:
# Outer Join
print("Outer Join:")
print(pd.merge(df_left, df_right, on="county", how="outer"))

Outer Join:
    county    cases  population
0  Autauga  18961.0     55869.0
1  Baldwin  67496.0    227131.0
2  Barbour   7027.0         NaN
3     Bibb   7692.0         NaN
4   Blount      NaN     59852.0